### ISSUE TITLE
Implement bit level update

### ISSUE THREAD

**Issue by kevemueller** [RustCrypto/traits#917] opened 2022-01-20 11:58 UTC
For hash functions that operate on bit level, exposing a bit-level update function would be nice.
E.g. 
The SHA-256 hash of the single bit input of `0` is `bd4f9e98beb68c6ead3243b1b4c7fed75fa4feaab1f84795cbd8a98676a2a375`.

**Comment by kevemueller** [comment] 2022-01-20 13:22
The use case is indeed academic, but nevertheless a question of completeness of implementation, e.g. looking at [KAT](https://csrc.nist.gov/CSRC/media/Projects/Hash-Functions/documents/SHA3-KATMCT1.pdf).

The most practical call interface would be an update function taking an input buffer and a second parameter with the number of bits to be taken from the input buffer.  By convention most significant bits are to be used - at least the few implementations I have seen do so.
Taken from above quoted document:
```
Len = 2
Msg = c0
MD = 1e1cea10a23697dc97b423c259842ac12ee679d6b43f088f3c32b26dbbfb0d79
```
This is the digest of the two bits `11`.
You could update (multi-)byte-wise until you reach the below-byte threshold and feed the remaining bits in.

I might be missing here something, but I don't understand your point with shifting bits in subsequent calls. Once you have updated the state with the number of bits, subsequent updates should not be affected, i.e. can use a bytewise update.

**Comment by newpavlov** [comment] 2022-01-22 00:35
>I might be missing here something, but I don't understand your point with shifting bits in subsequent calls.

Imagine you call a bit-level update function with 1 bit and then with 256 bytes. SHA-256 operates on 64 byte blocks, so buffering code would have to buffer the first bit, add 511 bits from the second call, and call the compress function on a resulting 512 bit buffer. Next it would have to process the remaining 1537 bits, but the problem is that they are not aligned to 8 bits, so instead of simply passing a pointer to the input slice, it would have to align blocks, meaning a bunch of shifts and ANDs on every processed block.

We could introduce bit-level variants of the [`*OutputCore` traits](https://docs.rs/digest/latest/digest/core_api/index.html) with blanket impls for the byte-level traits and leaving the `UpdateCore` trait as-is (i.e. it would be user responsibility to prepare byte-aligned blocks). Doing so would require introduction of a bit-level buffer type to [`block-buffer`](https://docs.rs/block-buffer) to be used as an input argument of those bit-level variants. Of course, we should be careful to not degrade the byte-level case in any way, e.g. by introducing inefficiencies to padding code which can not be removed by compiler.

**Comment by tarcieri** [comment] 2022-01-27 15:10
Is there actually precedent for other noteworthy cryptographic libraries supporting this?

It seems like the effort involved isn't justified by such a niche feature, especially if there's no interop story. As @newpavlov already noted, it significantly complicates buffering.

**Comment by newpavlov** [comment] 2023-11-12 06:40
Closing since the suggested feature has extremely low practical value and will significantly increase complexity of our crates with potential negative performance impact.

**Closed by newpavlov** 2023-11-12 06:40 UTC
Labels: enhancement, digest
