### ISSUE TITLE
Release new version of digest crate

### ISSUE THREAD

**Issue by devashishdxt** [RustCrypto/traits#176] opened 2020-06-08 03:44 UTC
Last version of `digest` crate was release 1 year ago and contains some old dependencies.

**Comment by newpavlov** [comment] 2020-06-08 07:42
Will close it as a duplicate of #43. I just need to introduce a final change and hopefully `digest v0.9` will be released in a day or two, followed by hash crate updates.

**Closed by newpavlov** 2020-06-08 07:42 UTC
Labels: duplicate
